### ISSUE TITLE
Como lidar com vários eventos no mesmo mês

### ISSUE THREAD

**Issue by rougeth** [rougeth/pythonnobrasil#3]

**Comment by giovanisleite** [comment]
_Mantendo o site com uma página_

Aparecerem apenas os meses com eventos e listar todos eventos em cada mês.

Prós:
- Uma página
- Meses vazios não ocupam espaço

Contra: 
- Retirar meses pode causar confusão no entendimento
- Meses quase vazios vão ocupar o mesmo espaço nas linhas que os meses bem movimentados

_Com mais de uma página_

Cada mês tem sua página e *acho* que não irá acontecer o problema de vários eventos no mesmo dia

**Comment by rougeth** [comment]
Fechando aqui, já que o layout do site mudou e a quantidade de eventos no mesmo mês já não é mais um problema.
