### ISSUE TITLE
Validar do yaml nos PR

### ISSUE THREAD

**Issue by rougeth** [rougeth/pythonnobrasil#31]

**Comment by Lrcezimbra** [comment]
Vou trabalhar nisso.

**Comment by rougeth** [comment]
@Lrcezimbra antes que você comece :) eu pretendia mudar de yaml para toml, anima fazer isso?

**Comment by Lrcezimbra** [comment]
Tu diz trocar o `conferencias` de `yaml` para `toml` ou o `.travis`?

**Comment by rougeth** [comment]
O conferencias mesmo.

Em qua, 2 de out de 2019 às 16:05, Lucas Rangel Cezimbra <
notifications@github.com> escreveu:

**Comment by Lrcezimbra** [comment]
Animo. Vou fazer essas modificações :+1:
