### ISSUE TITLE
Ordenar eventos listados no mesmo mês por data

### ISSUE THREAD

**Issue by rougeth** [rougeth/pythonnobrasil#5]
<img width="356" alt="screen shot 2018-03-04 at 00 42 55" src="https://user-images.githubusercontent.com/431892/36941918-0224eea6-1f45-11e8-8224-7eea0f369722.png">

Deveria ser:
- DG Canoas
- DG Bento Gonçalves
- Python Nordeste

**Comment by Lrcezimbra** [comment]
@rougeth esse já tá resolvido ou é por acaso que tá tudo ordenado no site atualmente?

**Comment by rougeth** [comment]
Resolvido!
